name: Deploy Godot Project to itch.io

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Export Godot Project
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Upload to itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: builds/  # Adjust this to the actual output directory from the export
          project: tintuna/classifiedtopsecret
          channel: html5
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.BUTLER_API_KEY }}
