name: Deploy Godot Project to itch.io

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Godot 4.3 Executable
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v4.3-stable_linux.x86_64

      - name: Download Godot 4.3 Export Templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/templates/4.3
          unzip Godot_v4.3-stable_export_templates.tpz -d ~/.local/share/godot/templates/4.3

      - name: Export Godot Project to ZIP
        run: |
          ./godot/Godot_v4.3-stable_linux.x86_64 --headless --export-pack "Web" ./builds/${{ github.ref_name}}.zip

      - name: Upload to itch.io
        uses: robpc/itchio-upload-action@v1
        with:
          path: builds/${{ github.ref_name }}
          project: tintuna/classifiedtopsecret
          channel: html5
          version: ${{ github.ref_name }}
          api-key: ${{ secrets.BUTLER_API_KEY }}
